version: "3"

# You'll probably have to do xhost +"local:docker@" on the host first
services:
  astudio:
    user: "${UID}:${GID}" 
    image: android-studio:latest
    hostname: astudio
    build: .
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - USER=${USER}
    volumes:
      - ${HOME}:${HOME}
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    network_mode: host

